### ISSUE TITLE
use nested properties as tag members

### ISSUE THREAD

**Issue by Boredude** [mailchimp/Firebase#18]
Is it possible to have nested properties as member tags?

I.E 

```
{
  emailAddress: "{MAILCHIMP_SUBSCRIBER_EMAIL_ADDRESS}",
  name: {
     first: "John",
    last: "Doe"
  }
  phoneNumber: "000-111-2222"
}
```

could I have `first` and `last` properties as tags on mailchimp?

**Comment by rcknr** [comment]
Since [lodash's `_.get()`](https://lodash.com/docs/#get) is used for getting the values from a document snapshot, you can use dot notation to define your mapping:
```
{
  "name.first": "FNAME",
  "name.last": "LNAME"
}
```

**Comment by barticus** [comment]
Closing, thanks @rcknr !
