### ISSUE TITLE
[docs] Move extra information in README to extension.yaml/PRE/POSTINSTALL

### ISSUE THREAD

**Issue by jhuleatt** [mailchimp/Firebase#2]
The readme is generated from the `generate-readme` npm script, so any information added to it manually (like the "required JSON keys" documentation that is currently in there) will be wiped out whenever the script is run. Additionally, the Firebase website/console/CLI don't pull from the readme.

Instead, use the following:

- **`extension.yaml`** to describe params, use the `description` field in extension.yaml ([params docs](https://firebase.google.com/docs/extensions/alpha/parameters#user-configured-parameters)). This way, the developer installing the extension will see the full description during the install flow.
- **`PREINSTALL.md`** for high-level description of what the extension does (for someone that's thinking about installing it). This will show on an extension's detail page on the Firebase website.
- **`POSTINSTALL.md`** should be used for any information needed after the extension is installed. This could be "see it in action" steps, or any advanced config/behavior you may want to explain to the installer. This will show in the Firebase console, and allows you to [reference parameters](https://firebase.google.com/docs/extensions/alpha/create-user-docs#reference-in-postinstall) that the installer has entered.

**Comment by barticus** [comment]
Closing as resolved in linked PR. Please raise another ticket if theres anything missing!
