### ISSUE TITLE
Open PRs

### ISSUE THREAD

**Issue by alexcastillo** [mailchimp/Firebase#22]
Hi there,

Thank you for the extension, it has saved me so much time 🙏🏽

I do see there are some important PRs that have been opened for a while. Is there a plan to review/merge them?

Open PRs: #10, #15, #16, #20

**Comment by barticus** [comment]
Hello!

I've merged a number and we're looking at doing a release soon with those. Others might need a bit more thought/work to do properly!

Closing this issue.
