### ISSUE TITLE
memberTagsHandler does not reflect changes from creation of user profile

### ISSUE THREAD

**Issue by mschmid** [mailchimp/Firebase#24]
I realized a strange behavior.
My memberTags are not synchronized anymore, since I changed how users are created.

I directly create users with `setDoc`:

```
let userProfile = {
  language: language,
  segments: [segment],
};
const userRef = doc(db, "users", uid);
setDoc(userRef, userProfile, { merge: true });
```

`addUserToList` does not reflect the user profile besides email, and `memberTagsHandler.onWrite` somehow does not synchronize the configured attributes `language` and `segment`. 

This is my Firebase Member Tags configuration:
`{ "memberTags": ["language", "segments"], "subscriberEmail": "email" }`

Subsequent changes to the memberTags fields are reflected to mailchimp correctly.

**Comment by barticus** [comment]
Hi @mschmid , 

When you create the userProfile above, are you including the field you've configured as `subscriberEmail`?
e.g. if you've set `"subscriberEmail": "email"` in your `mailchimpMemberTags`, i would expect your code to be:
```
let userProfile = {
  language: language,
  segments: [segment],
  email: "usersEmailHere@example.com"
};
```

**Comment by mschmid** [comment]
Hi @barticus thanks for the reply!! We need to set the language tag for all of our registered users by hand up to now ;-)

Seems like this is indeed the case - the `email` attribute is missing upon user creation. We will try out and confirm if it works.

**Comment by barticus** [comment]
Will close this @mschmid , reopen/create a new ticket if you're still seeing an issue!
