### ISSUE TITLE
MailChimp Firebase Integration only adds email and not first name and last name

### ISSUE THREAD

**Issue by dackers86** [mailchimp/Firebase#30]
Moving from https://github.com/firebase/extensions/issues/411

**Comment by barticus** [comment]
Hi @dackers86 ,
I can see this has been a long one for you! I'm trying to get across this request. Are you able to post the configuration you're using that is not setting the first and last name?

My understanding is that you will need to set up `Firebase Merge Fields Watch Path` and `Firebase Merge Fields Config` and then you can map your first and last name fields of your collection to FNAME and LNAME.

I wasn't sure from this question if you're specifically talking about from firebase auth?

Thanks,

**Comment by dackers86** [comment]
Thanks for the feedback @barticus.

I'll remind myself and review the issue to check the config fields

**Comment by barticus** [comment]
Closing this issue, if anyone is coming here from the root thread, please raise a new issue with up to date information.
