### ISSUE TITLE
[Question] Updating Mailchimp when a user changes their email in Firebase

### ISSUE THREAD

**Issue by JoBeDev** [mailchimp/Firebase#32]
Apologies if this has already been addressed but I couldn't find an answer for this anywhere. If a user changes their email address in my firebase app I want to automatically update their email address in Mailchimp to reflect the change. I can't figure out how to make this work using the current extension.

**Comment by barticus** [comment]
Currently the plugin will only write to the "new" email address.

We'll need to have a look into how this can be achieved.

**Comment by barticus** [comment]
We need to make a small tweak to the code to prefer the "previous" email address for the hash identifier, but after that we can update the mergeFields mapping to point your email address to the "EMAIL" field and achieve email updates.

**Comment by barticus** [comment]
Resolved with #46
