### ISSUE TITLE
[Question] How to use nested properties in Member tags config?

### ISSUE THREAD

**Issue by robertmaidlaAW** [mailchimp/Firebase#36]
Is it possible to refer to nested properties (maps) in the configuration?

For example, say I have a `users` Firebase collection with the following body:
```
{
"contactData": {
   "email": "...",
   "interests": ["...", "..."]
 }
}
```
How can I make the extension watch the changes in the `contactData` map? I've tried using the following syntax as the configuration without success: `{"subscriberEmail": "contactData.email", "memberTags": ["contactData.interests"]}`.

**Comment by barticus** [comment]
Hi @robertmaidlaAW , you can use json paths for the memberTags field, but not currently for the subscriberEmail field. I'll add a task to add that.

**Comment by barticus** [comment]
This work is done but pending release, so I'll close this issue.
