### ISSUE TITLE
[idea] Consider hosting Oauth flow on Firebase Hosting

### ISSUE THREAD

**Issue by jhuleatt** [mailchimp/Firebase#4]
If you use Firebase Hosting for the Oauth flow, instead of the long, google-centric URLs, you could use a custom domain, which would likely increase user trust.

- [Firebase Hosting custom domain docs](https://firebase.google.com/docs/hosting/custom-domain)
- [Firebase Hosting + Cloud Functions for Firebase docs](https://firebase.google.com/docs/hosting/functions)

**Comment by barticus** [comment]
Closing, SSL cert and custom domain have been put in place
