### ISSUE TITLE
Add a boolean flag for mergeFields to choose whether to pass to MailChimp the Firestore doc "latest" or "changed" values

### ISSUE THREAD

**Issue by alibad** [mailchimp/Firebase#43]
One of the limitations of the mergeFields function is that it only passes to MailChimp the fields that have changed within the Firestore doc. So if there are properties for an existing user (ex: Member Since = June 2020) and you enable the extension today, it won’t detect this as a changed property and will not update the MailChimp member with the value. It will always be empty in MailChimp as the extension compares changes in the Firestore doc itself rather than changes between the Firestore document and MailChimp.

Another symptom of this issue that I saw, if a document is being saved multiple times in a row with new values for new fields, the member in MailChimp ends up with a lot of empty fields. Might be a race condition, which could also be solved with ability to just write to the MailChimp mapped fields the latest values.

Is it possible to add a configurable flag in the extension to choose whether to always pass all the mapped field values (instead of just the changed ones in the Firestore doc)?

**Comment by barticus** [comment]
Hi @alibad ,
Thanks for raising this issue.

I think to meet this and future requirements we might need to update the structure of the mergeFields configuration so it can support an object format too.
E.g, instead of just this:

```js
{
    mergeFields: {
      firstName: "FNAME",
      lastName: "LNAME",
      phoneNumber: "PHONE",
    },
    subscriberEmail: "emailAddress"
}
```

It will also support

```js
{
    mergeFields: {
      firstName: {
        mailchimpFieldName: "FNAME",
        when: "changed|always",
        // extensibility for other features
      },
      lastName: "LNAME",
      phoneNumber: "PHONE",
    },
    subscriberEmail: "emailAddress"
}
```

Then:

1. The default behaviour and structure could be maintained
2. The "when" field would enable the functionality you've requested

Let me know if you have any input.

If you have details for the possible race condition, please raise in a new issue.

Regards

**Comment by alibad** [comment]
Yes what you’ve proposed works. When do you think this would make it into
the extension in prod?

**Comment by barticus** [comment]
Resolved in #55

**Comment by robinmitra** [comment]
Thanks for adding this feature! When do you expect to release this to the Firebase extension?

**Comment by barticus** [comment]
> Thanks for adding this feature! When do you expect to release this to the Firebase extension?

This is deployed in release 0.5.2 yesterday @robinmitra
