### ISSUE TITLE
Replace mailchimp-api-v3 with mailchimp-marketing package

### ISSUE THREAD

**Issue by barticus** [mailchimp/Firebase#44]
[mailchimp-marketing](https://www.npmjs.com/package/mailchimp-marketing) is a library package provided by Mailchimp's team for interacting with the marketing APIs.

This is maintained better than the existing package for this purpose, [mailchimp-api-v3](https://www.npmjs.com/package/mailchimp-api-v3).

**Comment by mjoycemilburn** [comment]
Hear, hear. I'm completely bemused by all this. Firebase functions provide a Node.js server environment and yet `const mailchimp = require("@mailchimp/mailchimp_marketing")` is rejected by Firebase deployment with a 'couldn't find module' error. Why? The mailchimp-api-v3 approach described here is extremely unattractive

**Comment by barticus** [comment]
I think this is the correct package: [@mailchimp/mailchimp_marketing](https://www.npmjs.com/package/@mailchimp/mailchimp_marketing)

**Comment by barticus** [comment]
Resolved by #66
