### ISSUE TITLE
[docs] Mismatched terminology in Oauth flow

### ISSUE THREAD

**Issue by jhuleatt** [mailchimp/Firebase#5]
In install flow, it says "API Key":

https://github.com/mailchimp/Firebase/blob/623b359b15b8a9c9f4fa68e91dd38336112ccb6d/extension.yaml#L162-L163

In result of Oauth flow, it says "Access token"

Which is the correct term that both should use?

**Comment by barticus** [comment]
Closing as resolved in linked PR.
