### ISSUE TITLE
[docs] Detail additional functionality to PREINSTALL.md and POSTINSTALL.md

### ISSUE THREAD

**Issue by jhuleatt** [mailchimp/Firebase#6]
Related to #2 

## PREINSTALL.md

Currently, the preinstall is a copy of the extension from the Firebase repo. Please update to describe the additional functionality provided by the Firestore triggers

## POSTINSTALL.md

Currently, the postinstall is a copy of the extension from the Firebase repo. Please update to describe how a developer can quickly test that the Firestore integration is working (i.e. "add a document that looks like this to this Firestore collection, and check X place in your Mailchimp dashboard to see the updated member")

**Comment by barticus** [comment]
Closing as resolved in linked PR.
