### ISSUE TITLE
Unable to install extension after config update, even after reverting (RESOURCE_ERROR)

### ISSUE THREAD

**Issue by jonnyk20** [mailchimp/Firebase#64]
Since Yesterday I've been unable to install the extension because of a `RESOURCE_ERROR`.

I've been using the extension for months with no issues, but yesterday I removed one of the keys from my `mergeFields` config, and when it tried to reconfigure there was an error `RESOURCE_ERROR` that prevented it (txt file with full logs and screenshots below). 
Here are the solutions I've tried so far:

- Thinking that my config change might have been the cause, I reset it back to what it was before but got the same errors. 
- Tried uninstalling and reinstalling with default config - same errors
- Tried installing from the CLI instead of the console - same errors

![Screen Shot 2023-04-30 at 2 51 35 PM](https://user-images.githubusercontent.com/16912653/235557206-1f7a5ff0-7246-4aa8-9e2a-8b092d88229f.png)

![Screen Shot 2023-04-30 at 2 51 44 PM](https://user-images.githubusercontent.com/16912653/235557209-9e4ab574-11ec-422e-983b-651ceff040d1.png)

[firebase_maichimp_error.txt](https://github.com/mailchimp/Firebase/files/11368900/firebase_maichimp_error.txt)

**Comment by javik6** [comment]
Same problem. With the Stripe extension it doesn't fail, but in the same project the Mailchimp extension always fails. Tested on various Firebase projects, both in console and with CLI and in various Cloud Functions locations.

**Comment by barticus** [comment]
Very strange. The extension has not been updated in a couple of months.

The error logs you've shared look like Functions are trying to perform typescript compilation, but this is not a typescript project.

This bears some investigation, although it smells a bit like a feature release gone wrong before Google I/O next Wednesday.

**Comment by javik6** [comment]
![Uploading Captura de pantalla 2023-05-02 a las 22.19.57.png…]()

I have added these changes manually in the Google Cloud Function console and have launched the manual deployment and it has worked.

**Comment by javik6** [comment]
I have added these changes manually in the Google Cloud Function console and have launched the manual deployment and it has worked:

1. Add empty variable: GOOGLE_NODE_RUN_SCRIPTS
2. Add run script in package.json: "gcp-build":""

**Comment by barticus** [comment]
Thanks @javik6 , I'll get a fix out ASAP.

**Comment by barticus** [comment]
This should be resolved in extension version 0.5.3.
If you run into issues after updating, you may need to uninstall, confirm the functions are deleted, then reinstall to make sure the functions are set up correctly in cloud functions.

**Comment by timeisgolden** [comment]
@barticus Hello, I need your help to resolve my issue.
I integrated the Mailchimp extension into Firebase.
I want to merge 'first_name' and 'last_name' to MailChimp.
This is the config I tried
<img width="649" alt="image" src="https://github.com/mailchimp/Firebase/assets/54345950/efcf1a41-5d3e-412c-9551-562fe58256a6">

I can see the following logs in the cloud console.
` A property named 'mergeFields' is required `

I thought I followed the configure as documentation.
how I can solve this issue?

Thanks in advance

**Comment by barticus** [comment]
Hi @timeisgolden , it looks like the quote marks around all the property names (e.g. `mergeFields`) are surrounded in unicode (directional) quote marks which might be causing a problem. Can you make sure all double quotes are the ascii `"`?

**Comment by timeisgolden** [comment]
@barticus you are right, I was adding `“`  quote marks, instead of `"`
I have solved the issue, Thanks so much.

**Comment by barticus** [comment]
No problem!
