### ISSUE TITLE
Authentication with Identity Platform

### ISSUE THREAD

**Issue by yellowhat** [mailchimp/Firebase#72]
Hi,
if I try to install this firebase extension with Firebase Authentication with Identity Platform configured it returns the following error:

```console
$ firebase deploy
...
i  extensions: By installing an extension instance onto a Firebase project, you accept the Firebase Extensions User Terms of Service: https://firebase.google.com/terms/extensions/user

Error: Some services used by this extension have not been set up on your Firebase project. To ensure this extension works as intended, you must enable these services by following the provided links, then retry this command

    * Firebase Authentication: authenticate and manage users from a variety of providers without server-side code.
      https://console.firebase.google.com/project/<redacted>/authentication/users
```

Is Authentication with Identity platform not supported by this extension?

Thanks

**Comment by barticus** [comment]
Hello, thanks for reaching out.

This error is normally caused from the service not yet being activated.

Can you please verify that you have Authentication activated in the Firebase Project you are installing the extension into?

I have created a new Firebase Project with only Authentication enabled, and upgraded it to Authentication with Identity Platform, and can confirm the extension functioned correctly when I added a new user.

I did quite a bit of digging to confirm that we are registering handlers [in the way suggested by the firebase documentation](https://firebase.google.com/docs/extensions/publishers/functions?hl=en&authuser=0#auth), and that there are not additional considerations for Firebase Authentication with Identity Platform.

Hope this gets it working!

**Comment by yellowhat** [comment]
Thanks for the reply.

My suspicion is that when you activate "Authentication" via the Firebase UI is enables other things that would allow your extension to work.

I am trying to automate the "Firebase Authentication" via terraform and the only way is by using the [Identity platform](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/identity_platform_config).

May I ask if you could create a new project from scratch and directly enable [Identity platform](https://cloud.google.com/identity-platform/docs/sign-in-user-email) and not use the Firebase UI?

Thanks

**Comment by barticus** [comment]
That seems like something you can test on your own.

But, based on what you are describing and the documents you have linked, I don't think you can do it with terraform. You need to activate Firebase Authentication and then upgrade to Identity Platform. It's possible you can achieve this via CLI/API, but the terraform module for Identity Platform is not using Firebase Authentication.

Regards

**Comment by yellowhat** [comment]
Well the test I describe is exactly what I was doing on the opening of the issue.

Interestingly when I use the automation above I can see that "Firebase Authentication" is indeed enabled.
The only difference I can see is:

![image](https://github.com/mailchimp/Firebase/assets/1692490/33a240c3-daa6-4616-8a4f-abe4115e8f6f)

becomes "Authentication with Identity Platform".

**Comment by yellowhat** [comment]
Curiously if I apply my workflow and use the UI to install the extension (click on `Manage Marketing with Mailchimp`), it installs it, instead running:

```bash
firebase deploy --only extensions --project <project>
```

return the error above

**Comment by barticus** [comment]
Hi @yellowhat ,

It sounds like a quirk of Firebase, possibly particularly when using Firebase Authentication with Identity platform.

The extension dictates which Firebase services must be available, but extensions cannot control activating those or how they are checked to be active. I'd recommend reaching out to Firebase support if you need further assistance.

Sorry we can't be of more help.
