### ISSUE TITLE
'Default' Merge Fields Not Updated for New User.  

### ISSUE THREAD

**Issue by TomJFox** [mailchimp/Firebase#76]
When creating a new user, my Firebase App calls Firebase to create an Authentication record, then immediately takes the user record created and updates it with base settings for a user.

```
        final user = await authManager.createAccountWithEmail(
          context,
          _model.signupEmailAddressController.text,
          _model.signuppasswordController.text,
        );
        if (user == null) {
          return;
        }
        await UserRecord.collection.doc(user.uid).update({
          ...createUserRecordData(
            accountStatus: 'Trial',
            otherfields: 'excluded')
        });

```
Unfortunately, this code is generated by a low code tool and not easily updateable.

What this seems to be doing is triggering both addToUserlist function AND mergeFieldsHandler function essentially in parallel.  In fact, based on logs, the mergeFieldsHandler seems to be being run first, before the addToUserList.  addToUserList even returns 'Attempted added user already in mailchimp audience', so the email seems to be added by the mergeFieldsHandler function rather than the addToUserList.  See this log extract:

```
receiveTimestamp 		resource.labels.function_name			sev	textPayload
2023-08-28T13:12:53.762097440Z	ext-mailchimp-firebase-sync-mergeFieldsHandler	DEBUG	Function execution started
2023-08-28T13:12:54.049401559Z	ext-mailchimp-firebase-sync-addUserToList	INFO	
2023-08-28T13:12:54.389499396Z	ext-mailchimp-firebase-sync-addUserToList	INFO	mailchimpMemberTags configuration not provided. mailchimpMemberTags {}
2023-08-28T13:12:54.389499396Z	ext-mailchimp-firebase-sync-addUserToList	INFO	mailchimpMemberEvents configuration not provided. mailchimpMemberEvents {}
2023-08-28T13:12:54.389499396Z	ext-mailchimp-firebase-sync-addUserToList	DEBUG	Function execution started
2023-08-28T13:12:54.389499396Z	ext-mailchimp-firebase-sync-addUserToList	INFO	Started execution of extension with configuration
2023-08-28T13:12:54.389499396Z	ext-mailchimp-firebase-sync-addUserToList	INFO	Adding user: <well formed user record> to Mailchimp audience: <audience ID>
2023-08-28T13:12:54.426181289Z	ext-mailchimp-firebase-sync-mergeFieldsHandler	DEBUG	Function execution took 489 ms, finished with status: 'ok'
2023-08-28T13:12:54.426181289Z	ext-mailchimp-firebase-sync-mergeFieldsHandler	DEBUG	Function execution started
2023-08-28T13:12:54.761198714Z	ext-mailchimp-firebase-sync-mergeFieldsHandler	DEBUG	Function execution took 213 ms, finished with status: 'ok'
2023-08-28T13:12:54.716643012Z	ext-mailchimp-firebase-sync-addUserToList	INFO	Attempted added user already in mailchimp audience
2023-08-28T13:12:54.716643012Z	ext-mailchimp-firebase-sync-addUserToList	DEBUG	Function execution took 540 ms, finished with status: 'ok'
2023-08-28T13:12:55.427063175Z	ext-mailchimp-firebase-sync-mergeFieldsHandler	INFO	
2023-08-28T13:12:55.427063175Z	ext-mailchimp-firebase-sync-mergeFieldsHandler	INFO	mailchimpMemberTags configuration not provided. mailchimpMemberTags {}
2023-08-28T13:12:55.760794431Z	ext-mailchimp-firebase-sync-mergeFieldsHandler	INFO	mailchimpMemberEvents configuration not provided. mailchimpMemberEvents {}

```

The result of the above is that the mailchimp mergeFields are not updated correctly with the 'default' values (eg.  'Trial' for account_status in particular).

One of the limitations with Cloud Firestore Triggers is that Ordering is not guaranteed.   [Reference Firebase Documentation](https://firebase.google.com/docs/functions/firestore-events?gen=2nd#limitations)  

Could there be a simlar issue here when these functions run out of order which would lead to mergefields not being properly set?  

Since the mergeField function compares old to new data and only passes data which changes, these 'default' fields are then not changed in later updates and are not passed to Mailchimp.  If I modify these fields after user creation, then the function works perfectly and the fields are updated, so the configuration is setup properly.

Hopefully you are able to help!

**Comment by TomJFox** [comment]
Perhaps a simple way to bypass the comparison of old and new such that the mergefield is always updated to the new value would be possible?

**Comment by barticus** [comment]
Hi @TomJFox ,

Can you share your configuration values you have set up, for Merge Fields in particular?

The situation you have outlined is not uncommon, and should not cause any issues. The addUserToList functionality is very basic, because there is not a lot of information available in Firebase Authentication. It only tries to create the user, and won't overwrite more data with less (this is why you get the line "Attempted added user already in mailchimp audience"). The mergeFieldsHandler will essentially do all the same if it does happen to be called first. 

Can you explain a bit more what you mean by "default" fields?

If you wanted to double check what data is sent when, you could clone the repo and have a look at `functions/tests/mergeFieldsHandler.test.js`.

Thanks

**Comment by TomJFox** [comment]
Hi @barticus 

Thanks for the reply.  By "default" fields, I mean those which are updated just after the authentication is created.  As in the code snippet above, account_status is set to Trial just after the user's authentication is created.  However, this update is not making it to Mailchimp.  Instead, the merge field remains blank.

However, after the user is created, if I manually change the account_status field in Firebase, the mergeFieldsHandler successfully copies the new value across to Mailchimp, so in this later update the configuration works successfully.

Here is the mergefield configuration. 

{ "mergeFields": { "display_name": "DISPLAY_NA", "account_status": "ACCOUNT_ST", "device": "DEVICE", "country": "COUNTRY", "setup_status": "SETUP_STAT", "person_count": "PERSON_COU", "pet_count": "PET_COUNT", "app_version": "APP_VERSIO" }, "subscriberEmail": "email" }

In Firebase my user records include:
display_name: string
account_status: string
device: string
country: string
setup_status: string
person_count: number
pet_count: number
app_version: string

In Mailchimp:
DISPLAY_NA: text
ACCOUNT_ST: text
DEVICE: radio buttons Android, iOS, or Web
COUNTRY: text
SETUP_STAT: text
PERSON_COU: number
PET_COUNT: number
APP_VERSIO: text

the first Firebase update after auth created sets:
```
            accountStatus: 'Trial',
            country: '',
            personCount: 0,
            petCount: 0,
            setupStatus: 'Step0',
            device: () {
              if (isiOS) {
                return 'iOS';
              } else if (isAndroid) {
                return 'Android';
              } else if (isWeb) {
                return 'Web';
              } else {
                return '';
              }

```
displayName and appVersion are set in later updates.

Hopefully this helps.

**Comment by TomJFox** [comment]
It might be possible to reproduce the issue if addUserToList function doesn't run.  Since, I have installed using Firebase Extensions, I do not want to delete the function (which seems to be the only way to prevent it from running).

I have attempted to reproduce the issue today and when I do not see the 'Attempted added user already in Mailchimp audience' message from addUserToList function, then the integration works successfully.

There seems to be a timing issue if addUserToList is delayed and mergeFieldHandler creates the Mailchimp user.

**Comment by TomJFox** [comment]
Could it be that due to timing, the mailchimp.lists.setListMember call from mergeFieldHandler completes first, then the mailchimp.lists.addListMember call from addUserToList completes second?  The issue might then be that the addListMember call does not include the merge fields and these are essentially overwritten.  

It is not clear from Mailchimp's documentation whether merge fields would be updated by addListMember call with no merge fields in the parameters as called by addUserToList when merge fields are already set.

**Comment by barticus** [comment]
Hi @TomJFox ,
The error `Attempted added user already in mailchimp audience` is from Mailchimp rejecting the call to add the member to the list, as they are already present in the list. So no overwriting would be occurring in this case.
I think the most likely culprit is you're setting the `accountStatus` field but your configuration is pointing at `account_status`. 
Please fix the casing/style of your field names (they should match) and then let me know if you're still experiencing this issue.

Regards

**Comment by TomJFox** [comment]
Hi @barticus,

The trouble with your proposal is that the integration works when the function complete in the correct order (add before merge).  I have cases with no change to the integration configuration where add completes without the message that the account already exists.  In these cases the merge function also completes and all the data expected is copied.

I'll see if I can reproduce this in a development environment.

**Comment by barticus** [comment]
Have you had a look at the document in firestore that results after all the calls are made?
I'm curious as to the naming convention inconsistency, there's definitely no code on the extension end that would transform property names from snake case to camel case.

**Comment by TomJFox** [comment]
Hi @barticus,

Yes, I have looked at Firebase.  The call to createUserRecordData handles the translation between cases.  It is easier to see in the very first post.

In Firebase, a user record is created with accout_status set to 'Trial'.  But when he  merge function completes first, the merge field in MailChimp is not set.

**Comment by barticus** [comment]
Hi @TomJFox ,

Thanks for the explanation, that makes the code and config make sense.

Unfortunately there's no debug mode where we can get higher fidelity logs.
I can see in your logs that the merge fields handler is called multiple times.
Can I confirm you're running a recent version of the extension (0.5.x)?

A few things you could try to help your investigation:
-  Add your own cloud function event listener to the same collection and log out the before and after data snapshots, it might help see what the data events are.
- You could pull down the repository and run it locally (details in "CONTRIBUTING") which should let you run other log statements you need.
- You could change your configuration and set `"when": "always"` on each field, to see if it helps.

Unfortunately I can't take this further without more information, as this is a case we test (with fairly similar code) before releasing builds.

**Comment by TomJFox** [comment]
I am using 0.5.2.

I will try downloading the extension locally as soon as I get some time at my machine hopefully in the next 2-3 days.  I'll let you know what I find.

I appreciate your help.  This is a problem I would like to see solved.

Thanks!

**Comment by TomJFox** [comment]
As the mergeFieldsHandler will also add users to the list and I am only using merge fields, I solved this by deleting the addUserToList function.
