### ISSUE TITLE
[BUG] Firestore triggers need to use `handler` syntax

### ISSUE THREAD

**Issue by jhuleatt** [mailchimp/Firebase#8]
The current syntax used by Firestore-triggered functions is: 

```js
functions.firestore.document(config.mailchimpMemberEvents.watch).onWrite(async (event, context) => {
```

However, extensions should use the [handler syntax](https://firebase.google.com/docs/extensions/alpha/construct-functions#firestore) to set up functions. It would be look like: 

```js
functions.handler.firestore.document.onWrite(async (change, context) => {
```

A user can configure the document that the extension watches by [configuring it with a param](https://firebase.google.com/docs/extensions/alpha/construct-functions#firestore:~:text=If%20you%20want%20users%20to%20be%20able%20to%20configure%20the%20document,parameter%20in%20your%20function's%20resource%20declaration%3A)

**Comment by barticus** [comment]
This change has been made and merged, closing issue.
